<?php
/**
 * @file
 * The webform component module.
 */

/**
 * Implements hook_theme().
 */
function webform_ytpicker_theme($existing, $type, $theme, $path) {
  return array(
    'webform_ytpicker_iframe' => array(
      'variables' => array(),
      'path' => drupal_get_path('module', 'webform_ytpicker') . '/tpl',
      'template' => 'webform-ytpicker-iframe',
    ),
  );
}

/**
 * Implements hook_webform_component_info().
 */
function webform_ytpicker_webform_component_info() {
  $components = array();
  $components['ytpicker'] = array(
    'label' => t('Youtube picker'),
    'description' => t('Add youtube movies users to choose between.'),
    'features' => array(
      'csv' => TRUE,
      'email' => TRUE,
      'email_address' => FALSE,
      'email_name' => FALSE,
      'required' => TRUE,
      'title_display' => FALSE,
      'title_inline' => FALSE,
      'conditional' => FALSE,
      'group' => FALSE,
      'spam_analysis' => FALSE,
      'attachment' => FALSE,
    ),
    'file' => 'components/ytpicker.inc',
  );
  return $components;
}

/**
 * The component Form.
 */
function webform_ytpicker_component_form($component) {
  $form = array();
  $form['extra']['yt'] = array(
    '#type' => 'fieldset',
    '#title' => 'Youtube picker',
  );
  $use_nodes = isset($component['extra']['yt']['use_nodes']) ? $component['extra']['yt']['use_nodes'] : false;
  $form['extra']['yt']['use_nodes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use nodes with youtube field'),
    '#default_value' => $use_nodes,
  );
  $contenttypes = node_type_get_types();
  $field_options = array();
  $field_options[0] = t(' -- pick a contenttype and field -- ');
  foreach($contenttypes as $key => $ct) {
    $options[$key] = $ct->name;
  }

  $fields = field_info_fields();
  foreach($fields as $field) {
    if ($field['type'] == 'youtube') {
      foreach($field['bundles'] as $bundle_key => $bundle) {
        $field_options[$bundle_key][$field['field_name']] = $field['field_name'];
      }
    }
  }

  $nodes_field = isset($component['extra']['yt']['nodes_field']) ? $component['extra']['yt']['nodes_field'] : false;
  $form['extra']['yt']['nodes_field'] = array(
    '#type' => 'select',
    '#title' => t('Contenttype with youtube field'),
    '#default_value' => $nodes_field,
    '#options' => $field_options,
  );
  $width = isset($component['extra']['yt']['width']) ? $component['extra']['yt']['width'] : '560';
  $form['extra']['yt']['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Youtube video width'),
    '#default_value' => $width,
  );
  $height = isset($component['extra']['yt']['height']) ? $component['extra']['yt']['height'] : '315';
  $form['extra']['yt']['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Youtube video height'),
    '#default_value' => $height,
  );
  $form['extra']['yt']['ytp'] = array(
    '#type' => 'textarea',
    '#title' => t("Youtube video's"),
    '#description' => t('enter them as following: "Name|youtube_url'),
    '#default_value' => $component['extra']['yt']['ytp'],
  );
  return $form;
}
